# Generated by Django 6.0.6 on 2026-06-25 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('current_floor', models.IntegerField(default=1)),
                ('direction', models.CharField(default='IDLE', max_length=10)),
                ('is_moving', models.BooleanField(default=False)),
                ('is_emergency', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_floor', models.IntegerField()),
                ('destination_floor', models.IntegerField()),
                ('direction', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elevator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SmartElevator.elevator')),
            ],
        ),
    ]
